spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jooqh2bitand
    username: sa
    password: sa
  jooq:
    sql-dialect: H2
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml
